version: '3.3'
services:
  sslchecker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOOK_URLS: "https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXX"
      HOSTNAMES: "fivexl.io"
      HEALTH_CHECK_MATCHER: "200-399"
      CERTIFICATE_EXPIRATION_NOTICE_DAYS: "7"