version: '3.3'
services:
  sslchecker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOOK_URL: "https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXX"
      HOSTNAMES: "fivexl.io"
      CERTIFICATE_EXPIRATION_NOTICE_DAYS: "7"